### ISSUE TITLE
Add support to show directory entries recursively

### ISSUE THREAD

**Issue by alexherbo2** [TeddyDD/kakoune-edit-or-dir#5]
I added this functionality on <kbd>R</kbd> – for _recursive_ as for the command-lines `-R` flag.

It draws inspiration from @occivink’s [filetree](https://github.com/occivink/kakoune-filetree).

**Comment by TeddyDD** [comment]
Problems with this feature:
- can hang Kakoune if you try to run it directory like /home (too big output)
- even if you configure max depth it's still can output too much data
- we can handle that with `timeout` or `head` but then plugin won't output corret data every time
- output of ls -R isn't nice to read, we could try to parse `tree` output but that is quite hardcore idea

I think it's out of project's scope. It's easier and less error prone to integrate external file browser for this task (or use fzf)

**Comment by alexherbo2** [comment]
![Demo](https://github.com/alexherbo2/edit-directory.kak/raw/master/images/demo.gif)

I was thinking to `find` for the recursive part, like @occivink.

The feature is not exposed through an option but a mapping, so there is no recursion when opening a directory.  It’s always no recursive, unless you type <kbd>R</kbd> like in the demo.

We could avoid the blocking part by using a FIFO – like in [grep](https://github.com/mawww/kakoune/blob/master/rc/core/grep.kak).

**Comment by TeddyDD** [comment]
Both issues still apply:
- using grep from $HOME slows down Kakoune to crawl despite FIFO. Maybe I'v got more files than you, dunno
- result is flat list of files that is not really readable. FZF/lf/ranger will be better at navigating and opening multiple files
