### ISSUE TITLE
error at first run

### ISSUE THREAD

**Issue by jgmtzmd** [TeddyDD/kakoune-edit-or-dir#6]
put in my kakrc

`source /path/to/edit-or-dir.kak
`

and when in kak i try run the command but get this error

`'evaluate-commands' 1:1 'try' wrong argument count`

any help or direction? thanks.

**Comment by TeddyDD** [comment]
What version of Kakoune do you use?

**Comment by jgmtzmd** [comment]
in opensuse leap 15

2018.04.13-lp150.2.1

**Comment by TeddyDD** [comment]
I can't reproduce this, please ensure it's not an issue with other plugin. Run `kak -n` and source `edit-or-dir.kak` manually; `:source <path to edit-or-dir.kak>`. Paste content of debug buffer here as well.

**Comment by jgmtzmd** [comment]
run kak -n.
source from within kakoune..
`
:source /path..
`

and i get the same error.
anyway my setup may be a little weird: opensuse -> screen -> xonsh. So maybe the problem is there. do you depend on bash in any way?

**Comment by TeddyDD** [comment]
No, all `%sh` expansions should be POSIX compatible. Kakoune uses /bin/sh anyway and it should be POSIX.

 Try to run Kakoune from other shell, just to make sure.

**Comment by jgmtzmd** [comment]
tried with pure bash and it is the same. even invoking it from tty directly (not terminal emulator).

**Comment by TeddyDD** [comment]
Ok, I tried xonsh and it seems to work fine for me. I'll try to pull leap docker image and try to reproduce there

**Comment by TeddyDD** [comment]
damn, I must be tired...
I just realized: Leap has outdated version of Kakoune. My plugins support only latest stable version: Kakoune v2018.09.04

You might try to apply this patch but I don't guarantee it will work.

```diff
diff --git i/edit-or-dir.kak w/edit-or-dir.kak
index d5e3c3..467de0 100644
--- i/edit-or-dir.kak
+++ w/edit-or-dir.kak
@@ -1,5 +1,5 @@
 define-command edit-or-dir -file-completion -params .. %{
-    evaluate-commands %sh{
+    %sh{
         echo "try %{ delete-buffer! *dir* }"
         arg="$1"
         [ -z "$arg" ] && arg=$(pwd)
@@ -26,7 +26,7 @@ declare-option -hidden str edit_or_dir_hidden ''
 define-command -hidden -params 1 edit-or-dir-display-dir %{
     edit -scratch *dir*
     set-option window filetype 'file_select'
-    evaluate-commands %sh{
+    %sh{
         keys="ls<space>$kak_opt_edit_or_dir_hidden<space>-p<space>--group-directories-first<space><ret>xd"
         if [ -z $kak_opt_edit_or_dir_hidden ]; then
             keys="!echo<space>../<space>&&<space> $keys gg"
@@ -60,7 +60,7 @@ hook global WinSetOption filetype=file_select %{
 }
 
 define-command -hidden edit-or-dir-toggle-hidden %{
-    evaluate-commands %sh{
+    %sh{
         if [ -z $kak_opt_edit_or_dir_hidden ]; then
             echo "set-option global edit_or_dir_hidden '-a'"
         else
```
