### ISSUE TITLE
No dir listing under macos

### ISSUE THREAD

**Issue by vbauerster** [TeddyDD/kakoune-edit-or-dir#7]
❯ zsh --version
zsh 5.6.2 (x86_64-apple-darwin18.0.0)

**Comment by vbauerster** [comment]
❯ zsh --version
zsh 5.6.2 (x86_64-apple-darwin18.0.0)

**Comment by TeddyDD** [comment]
What Kakoune version do you use?

I guess ls on mac os doesn't support `--group-directories-first` flag. I'll replace it with something portable.

**Comment by TeddyDD** [comment]
Please check if it works on `fix-7` branch https://github.com/TeddyDD/kakoune-edit-or-dir/tree/fix-7

**Comment by vbauerster** [comment]
Confirm, it works in branch `fix-7`
